package com.jastt.dal.entities;

// Generated 05.11.2014 13:34:24 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermissionEntity generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION", schema = "PUBLIC", catalog = "PUBLIC")
public class PermissionEntity implements java.io.Serializable {

	private PermissionEntityId id;
	private UserEntity userEntity;
	private ProjectEntity projectEntity;

	public PermissionEntity() {
	}

	public PermissionEntity(PermissionEntityId id, UserEntity userEntity,
			ProjectEntity projectEntity) {
		this.id = id;
		this.userEntity = userEntity;
		this.projectEntity = projectEntity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", nullable = false)) })
	public PermissionEntityId getId() {
		return this.id;
	}

	public void setId(PermissionEntityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false, insertable = false, updatable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false, insertable = false, updatable = false)
	public ProjectEntity getProjectEntity() {
		return this.projectEntity;
	}

	public void setProjectEntity(ProjectEntity projectEntity) {
		this.projectEntity = projectEntity;
	}

}
