// default package
// Generated 31.10.2014 19:02:31 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissionId generated by hbm2java
 */
@Embeddable
public class PermissionId implements java.io.Serializable {

	private int userId;
	private int projectId;

	public PermissionId() {
	}

	public PermissionId(int userId, int projectId) {
		this.userId = userId;
		this.projectId = projectId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "PROJECT_ID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermissionId))
			return false;
		PermissionId castOther = (PermissionId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
