package com.sample.dal.entities;

// Generated Oct 30, 2013 9:27:58 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeacherReviewEntity generated by hbm2java
 */
@Entity
@Table(name = "TEACHER_REVIEW")
public class TeacherReviewEntity implements java.io.Serializable {

	private Integer id;
	private StudentEntity studentEntity;
	private TeacherEntity teacherEntity;
	private Date reviewDate;
	private String reviewText;
	private int rating;

	public TeacherReviewEntity() {
	}

	public TeacherReviewEntity(StudentEntity studentEntity, TeacherEntity teacherEntity, Date reviewDate,
			String reviewText, int rating) {
		this.studentEntity = studentEntity;
		this.teacherEntity = teacherEntity;
		this.reviewDate = reviewDate;
		this.reviewText = reviewText;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDENT_ID", nullable = false)
	public StudentEntity getStudentEntity() {
		return this.studentEntity;
	}

	public void setStudentEntity(StudentEntity studentEntity) {
		this.studentEntity = studentEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEACHER_ID", nullable = false)
	public TeacherEntity getTeacherEntity() {
		return this.teacherEntity;
	}

	public void setTeacherEntity(TeacherEntity teacherEntity) {
		this.teacherEntity = teacherEntity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REVIEW_DATE", nullable = false, length = 26)
	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	@Column(name = "REVIEW_TEXT", nullable = false, length = 4096)
	public String getReviewText() {
		return this.reviewText;
	}

	public void setReviewText(String reviewText) {
		this.reviewText = reviewText;
	}

	@Column(name = "RATING", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

}
