package com.jastt.dal.entities;

// Generated 05.11.2014 13:34:24 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissionEntityId generated by hbm2java
 */
@Embeddable
public class PermissionEntityId implements java.io.Serializable {

	private int userId;
	private int projectId;

	public PermissionEntityId() {
	}

	public PermissionEntityId(int userId, int projectId) {
		this.userId = userId;
		this.projectId = projectId;
	}

	@Column(name = "USER_ID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "PROJECT_ID", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermissionEntityId))
			return false;
		PermissionEntityId castOther = (PermissionEntityId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getProjectId() == castOther.getProjectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getProjectId();
		return result;
	}

}
