package com.jastt.dal.entities;

// Generated 05.11.2014 13:34:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ServerEntity generated by hbm2java
 */
@Entity
@Table(name = "SERVER", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = {
		@UniqueConstraint(columnNames = "URL"),
		@UniqueConstraint(columnNames = "NAME") })
public class ServerEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String url;
	private Set<UserEntity> userEntities = new HashSet<UserEntity>(0);
	private Set<ProjectEntity> projectEntities = new HashSet<ProjectEntity>(0);

	public ServerEntity() {
	}

	public ServerEntity(String name, String url) {
		this.name = name;
		this.url = url;
	}

	public ServerEntity(String name, String url, Set<UserEntity> userEntities,
			Set<ProjectEntity> projectEntities) {
		this.name = name;
		this.url = url;
		this.userEntities = userEntities;
		this.projectEntities = projectEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL", unique = true, nullable = false, length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity")
	public Set<UserEntity> getUserEntities() {
		return this.userEntities;
	}

	public void setUserEntities(Set<UserEntity> userEntities) {
		this.userEntities = userEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity")
	public Set<ProjectEntity> getProjectEntities() {
		return this.projectEntities;
	}

	public void setProjectEntities(Set<ProjectEntity> projectEntities) {
		this.projectEntities = projectEntities;
	}

}
