package com.jastt.dal.entities;

// Generated 07.12.2014 16:34:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.jastt.dal.entities.GenericDalEntity;

/**
 * ServerEntity generated by hbm2java
 */
@Entity
@Table(name = "SERVER", schema = "PUBLIC", catalog = "PUBLIC", uniqueConstraints = @UniqueConstraint(columnNames = "URL"))
public class ServerEntity extends GenericDalEntity<Integer> implements java.io.Serializable {

	private String url;
	private Set<UserEntity> userEntities = new HashSet<UserEntity>(0);
	private Set<ProjectEntity> projectEntities = new HashSet<ProjectEntity>(0);

	public ServerEntity() {
	}

	public ServerEntity(String url) {
		this.url = url;
	}

	public ServerEntity(String url, Set<UserEntity> userEntities,
			Set<ProjectEntity> projectEntities) {
		this.url = url;
		this.userEntities = userEntities;
		this.projectEntities = projectEntities;
	}


	@Column(name = "URL", unique = true, nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity")
	public Set<UserEntity> getUserEntities() {
		return this.userEntities;
	}

	public void setUserEntities(Set<UserEntity> userEntities) {
		this.userEntities = userEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverEntity")
	public Set<ProjectEntity> getProjectEntities() {
		return this.projectEntities;
	}

	public void setProjectEntities(Set<ProjectEntity> projectEntities) {
		this.projectEntities = projectEntities;
	}

}
