package com.sample.dal.entities;

// Generated Oct 30, 2013 9:27:58 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StudentEntity generated by hbm2java
 */
@Entity
@Table(name = "STUDENT")
public class StudentEntity implements java.io.Serializable {

	private Integer id;
	private UserEntity userEntity;
	private String studentNo;
	private Set<TeacherReviewEntity> teacherReviewEntities = new HashSet<TeacherReviewEntity>(0);

	public StudentEntity() {
	}

	public StudentEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	public StudentEntity(UserEntity userEntity, String studentNo, Set<TeacherReviewEntity> teacherReviewEntities) {
		this.userEntity = userEntity;
		this.studentNo = studentNo;
		this.teacherReviewEntities = teacherReviewEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "STUDENT_NO", length = 64)
	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentEntity")
	public Set<TeacherReviewEntity> getTeacherReviewEntities() {
		return this.teacherReviewEntities;
	}

	public void setTeacherReviewEntities(Set<TeacherReviewEntity> teacherReviewEntities) {
		this.teacherReviewEntities = teacherReviewEntities;
	}

}
