package com.sample.dal.entities;

// Generated Oct 30, 2013 9:27:58 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SubjectEntity generated by hbm2java
 */
@Entity
@Table(name = "SUBJECT", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class SubjectEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<TeacherCourseEntity> teacherCourseEntities = new HashSet<TeacherCourseEntity>(0);

	public SubjectEntity() {
	}

	public SubjectEntity(String name) {
		this.name = name;
	}

	public SubjectEntity(String name, String description, Set<TeacherCourseEntity> teacherCourseEntities) {
		this.name = name;
		this.description = description;
		this.teacherCourseEntities = teacherCourseEntities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 2048)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjectEntity")
	public Set<TeacherCourseEntity> getTeacherCourseEntities() {
		return this.teacherCourseEntities;
	}

	public void setTeacherCourseEntities(Set<TeacherCourseEntity> teacherCourseEntities) {
		this.teacherCourseEntities = teacherCourseEntities;
	}

}
