package com.sample.dal.entities;

// Generated Oct 30, 2013 9:27:58 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherCourseEntity generated by hbm2java
 */
@Entity
@Table(name = "TEACHER_COURSE")
public class TeacherCourseEntity implements java.io.Serializable {

	private Integer id;
	private CourseEntity courseEntity;
	private SubjectEntity subjectEntity;
	private TeacherEntity teacherEntity;
	private int hours;

	public TeacherCourseEntity() {
	}

	public TeacherCourseEntity(CourseEntity courseEntity, SubjectEntity subjectEntity, TeacherEntity teacherEntity,
			int hours) {
		this.courseEntity = courseEntity;
		this.subjectEntity = subjectEntity;
		this.teacherEntity = teacherEntity;
		this.hours = hours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID", nullable = false)
	public CourseEntity getCourseEntity() {
		return this.courseEntity;
	}

	public void setCourseEntity(CourseEntity courseEntity) {
		this.courseEntity = courseEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBJECT_ID", nullable = false)
	public SubjectEntity getSubjectEntity() {
		return this.subjectEntity;
	}

	public void setSubjectEntity(SubjectEntity subjectEntity) {
		this.subjectEntity = subjectEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEACHER_ID", nullable = false)
	public TeacherEntity getTeacherEntity() {
		return this.teacherEntity;
	}

	public void setTeacherEntity(TeacherEntity teacherEntity) {
		this.teacherEntity = teacherEntity;
	}

	@Column(name = "HOURS", nullable = false)
	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

}
